### PR TITLE
Al-amin/handle_website_status_cookie_on_VPN_change

### PR DESCRIPTION
**Pull request by alamin-deriv**
Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Comment by sean-binary** [comment]
Could we just change the cookie duration to none? @alamin-deriv @prince-deriv

**Comment by alamin-deriv** [comment]
> 

@sean-binary how and if we're able to do that we don't need these changes?

**Comment by sean-binary** [comment]
That's right. There's a `COOKIE_EXPIRY_DAYS` inside useWebsiteStatus hook.

**Comment by alamin-deriv** [comment]
> That's right. There's a `COOKIE_EXPIRY_DAYS` inside useWebsiteStatus hook.

Okay sure, let me look into it

**Review by sean-binary — DISMISSED** [review]

**Review by sean-binary — APPROVED** [review]

**Review by sean-binary — APPROVED** [review]

**Pull request merged**
