### PR TITLE
fix: checking semantic

### PR DESCRIPTION
**Pull request by ashraf-deriv**
Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Review by maryia-binary — DISMISSED** [review]

**Review by iman-fs — DISMISSED** [review]

**Review by michio-rework — CHANGES_REQUESTED** [review]
There are no changes in `package.json` file and yet we have changes on package-lock.json, please revert this file back to the original file on `master` branch and run `npm ci`. please make sure you are using node `v17.x` and npm `v8.x`, thanks :pray:

**Review by ali-hosseini-fs — DISMISSED** [review]

**Comment by ashraf-deriv** [comment]
> There are no changes in `package.json` file and yet we have changes on package-lock.json, please revert this file back to the original file on `master` branch and run `npm ci`. please make sure you are using node `v17.x` and npm `v8.x`, thanks 🙏

@michio-rework  should we use node 'v17.x' ?

**Comment by michio-rework** [comment]
> There are no changes in `package.json` file and yet we have changes on package-lock.json, please revert this file back to the original file on `master` branch and run `npm ci`. please make sure you are using node `v17.x` and npm `v8.x`, thanks pray

It's decided that we use the LTS version of node, which is 16.x. we should no longer use node 17.x

**Comment by ashraf-deriv** [comment]
> > There are no changes in `package.json` file and yet we have changes on package-lock.json, please revert this file back to the original file on `master` branch and run `npm ci`. please make sure you are using node `v17.x` and npm `v8.x`, thanks pray
> 
> It's decided that we use the LTS version of node, which is 16.x. we should no longer use node 17.x

Ok sure👍

**Review by ali-hosseini-fs — APPROVED** [review]

**Review by michio-rework — APPROVED** [review]

**Comment by ali-hosseini-fs** [comment]
@ashraf-deriv would you please check why there's `package-lock.json` in your changes?

**Review by ali-hosseini-deriv — APPROVED** [review]

**Pull request closed without merging**
