### PR TITLE
notes changes payment methods

### PR DESCRIPTION
**Pull request by eduard-deriv**
Changes:

-   notes changes payment methods

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Comment by DerivFE** [comment]
| Name | Result |
| :--- | :------ |
| **Build status**  | Building 🔨 |
| **Action URL**  | [Visit Action](https://github.com/binary-com/deriv-com/actions/runs/6796100253) |

**Comment by DerivFE** [comment]
| Name | Result |
| :--- | :------ |
| **Build status**  | Building 🔨 |
| **Action URL**  | [Visit Action](https://github.com/binary-com/deriv-com/actions/runs/6796123407) |

**Comment by DerivFE** [comment]
| Name | Result |
| :--- | :------ |
| **Build status**  | Building 🔨 |
| **Action URL**  | [Visit Action](https://github.com/binary-com/deriv-com/actions/runs/6796160798) |

**Comment by DerivFE** [comment]
**Preview Link**: https://translation-1831-tra.deriv-com-preview-links.pages.dev
| Name | Result |
| :--- | :------ |
| **Build status**  | Completed ✅ |
| **Preview URL**  | [Visit Preview](https://translation-1831-tra.deriv-com-preview-links.pages.dev) |
| **Action URL**  | [Visit Action](https://github.com/binary-com/deriv-com/actions/runs/6796160798) |

**Review by konstantinosG-deriv — APPROVED** [review]

**Review by mitra-deriv — APPROVED** [review]

**Review by aswathy-deriv — APPROVED** [review]

**Pull request merged**
