### PR TITLE
Hasan/fix: productboard iframe firefox issue

### PR DESCRIPTION
**Pull request by hasan-deriv**
Changes:

-  p2p Product board firefox issue fixed

### CODE REVIEW

**Review by review-deriv — COMMENTED** [review]
PR description is too short. You can use this format:

```
# Description
This is a summary of the changes. This should describe why do we need this change.
Whys and Hows come here.

# Cards
* https://clickup.com/12345
* https://clickup.com/12346

```

**Review by review-deriv — COMMENTED** [review]
PR description is too short. You can use this format:

```
# Description
This is a summary of the changes. This should describe why do we need this change.
Whys and Hows come here.

# Cards
* https://clickup.com/12345
* https://clickup.com/12346

```

**Comment by dan-deriv** [comment]
@hasan-deriv @habib-deriv pls change title of PR according to the pattern

**Review by habib-deriv — APPROVED** [review]
LGTM

**Pull request merged**
