### PR TITLE
fiona /  convert Image to code

### PR DESCRIPTION
**Pull request by fiona-deriv**
Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [x] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Review by kevinw-binary — COMMENTED** [review]
Hi @fiona-deriv  I just saw the testlink however the text on the formula seems dislocated because of the font-size would be better to restyle it )

**Comment by fiona-deriv** [comment]
sure, gonna restyle it

**Comment by sean-binary** [comment]
image
Seems like there are some overlaps on translated text, maybe you need to restrict their max widths and wrap them if they exceed it.

image
This section is not following the full width of it's parent container.

**Comment by sean-binary** [comment]
Please help to update this section to full width accordingly as well.
image

**Comment by sean-binary** [comment]
Please help to rebase this PR 🙏

**Pull request closed without merging**
