### PR TITLE
Meenu/Pr 72454 pull latest price for calculators

### PR DESCRIPTION
**Pull request by meenakshi-deriv**
Changes:

 -  Used "tick" api to get the spot price
 -  Removed old markets and added new ones

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Comment by habib-deriv** [comment]
Screenshot 2022-08-11 at 11 01 15 AM

After clearing every input field the clicking on cross icon is showing onclick it genrates an error in the console

**Review by michio-rework — CHANGES_REQUESTED** [review]

**Comment by michio-rework** [comment]
when the first request is sent to the server to get `symbols` if we select a market there will be an error in the console. either we have to disable the form until the we receive the `symbol`s data or we have to update the onChange function to handle this.

**Review by habib-deriv — APPROVED** [review]
LGTM

**Review by habib-deriv — APPROVED** [review]
LGTM

**Pull request merged**
