### PR TITLE
Al-amin/[Mobile responsive] Not able to scroll down to login with existing account in EU

### PR DESCRIPTION
**Pull request by alamin-deriv**
Changes:

-   [Mobile responsive] Not able to scroll down to login with existing account in EU

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Review by prince-deriv — DISMISSED** [review]

**Comment by sean-binary** [comment]
> LGTM @alamin-deriv
> 
> @sean-binary this is one example of limitation we have where we need to add `!important` to override the css rule, but in reality this `margin-top: 3.75rem` should be prioritized because it's a rule for specific size but since that's how `styled-component` works, we need to change our main components to be able to override css rules in specific sizes by default.

If not mistaken, passing in the `mt` as a prop to the component rather than declaring it in the CSS template literal should solve that specificity issue.

**Comment by prince-deriv** [comment]
> If not mistaken, passing in the `mt` as a prop to the component rather than declaring it in the CSS template literal should solve that specificity issue.

The `LoginText` contains a `margin-top` rule for desktop and because of how `styled-components` prioritize the css rules, It will always override the ones we pass in the props

```
const LoginText = styled(Text)`
    text-align: center;
    align-self: center;
    margin-top: 1.6rem;

    @media ${device.tabletL} {
        font-size: 2rem;
    }
```

**Comment by alamin-deriv** [comment]
> > If not mistaken, passing in the `mt` as a prop to the component rather than declaring it in the CSS template literal should solve that specificity issue.
> 
> The `LoginText` contains a `margin-top` rule for desktop and because of how `styled-components` prioritize the css rules, It will always override the ones we pass in the props
> 
> ```
> const LoginText = styled(Text)`
>     text-align: center;
>     align-self: center;
>     margin-top: 1.6rem;
> 
>     @media ${device.tabletL} {
>         font-size: 2rem;
>     }
> ```

``

**Comment by sean-binary** [comment]
> > If not mistaken, passing in the `mt` as a prop to the component rather than declaring it in the CSS template literal should solve that specificity issue.
> 
> The `LoginText` contains a `margin-top` rule for desktop and because of how `styled-components` prioritize the css rules, It will always override the ones we pass in the props
> 
> ```
> const LoginText = styled(Text)`
>     text-align: center;
>     align-self: center;
>     margin-top: 1.6rem;
> 
>     @media ${device.tabletL} {
>         font-size: 2rem;
>     }
> ```

Yep so for components where responsive styles are required, we can do as such:

```jsx
<LoginText mt="1.6rem" tablet={{ mt: "3.75rem" }}></LoginText>

```
instead of declaring it in the CSS template literal above.

**Review by sean-binary — APPROVED** [review]

**Pull request merged**
