### PR TITLE
Al-amin/added commit lint to follow git guidelines

### PR DESCRIPTION
**Pull request by alamin-deriv**
Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [x] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Comment by alamin-deriv** [comment]
We have a set of precise rules over how our git commit messages can be formatted. This leads to more readable messages that are easy to follow when looking through the project history.

[](https://github.com/binary-com/deriv-com/blob/master/documents/git-best-practices.md#changing-base-branch)Must be one of the following:

- build: Changes that affect the build system or external dependencies (example scopes: gatsby config, gatsby browser, gatsby node, or gatsby ssr)
- chores: Add or Changes on packages or external dependencies
- ci: Changes to our CI configuration files and scripts (example scopes: Docker, nginx conf)
- docs: Documentation only changes
- feat: A new feature
- fix: A bug fix
- perf: A code change that improves performance
- refactor: A code change that neither fixes a bug nor adds a feature
- style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- text: Adding text or updating text only
- empty: Rare cases for re-deploying when deployment server is down
- revert: A commit reverts a previous commit

**Comment by sean-binary** [comment]
This is nice @alamin-deriv. Could you please update your npm version globally by `npm install -g npm@latest` and running `npm install` again?

**Comment by alamin-deriv** [comment]
> This is nice @alamin-deriv. Could you please update your npm version globally by `npm install -g npm@latest` and running `npm install` again?

@sean-binary Done

**Review by sean-binary — APPROVED** [review]
LGTM

**Pull request merged**
