### PR TITLE
Habib/broken chinese text responsive

### PR DESCRIPTION
**Pull request by ShuvoHabib**
Changes:

Issue: Broken text in Responsive page for VI and Chinese languages

Steps to reproduce:
1.Go to deriv.com in Responsive mode.
2.Navigate to https://deriv.com/markets#synthetic
3.Navigate to https://deriv.com/markets#forex

Issue 1.Change the language to "VI" Observe the text in tabs
Issue 2.Change the language to Chinese and observe the text in tabs

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Comment by suthesan-deriv** [comment]
Should we abstract TabMultiplierIcon, TabOptionIcon and TabMarginIcon into a single component maybe TabIcon since it's using the same css?

**Comment by sean-binary** [comment]
image
I think this might be a little too small for tablet-ish screen widths. Might be worth having a short call with the designer to discuss an agreed approach for this. 😬

**Comment by ShuvoHabib** [comment]
> Should we abstract TabMultiplierIcon, TabOptionIcon and TabMarginIcon into a single component maybe TabIcon since it's using the same css?

Yeah, sounds like a good plan, as they are doing the same thing.

**Comment by ShuvoHabib** [comment]
> image
> I think this might be a little too small for tablet-ish screen widths. Might be worth having a short call with the designer to discuss an agreed approach for this. 😬

We have a lot of space in tab. I think just reducing margin left from Mobile will be enough.

**Review by sean-binary — APPROVED** [review]

**Review by yashim-deriv — DISMISSED** [review]

**Review by sean-binary — APPROVED** [review]

**Pull request merged**
