### PR TITLE
fiona / update paris' office physical location

### PR DESCRIPTION
**Pull request by fiona-deriv**
Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Comment by sean-binary** [comment]
Hey @fiona-deriv, map is currently breaking for widths > 1980px.

**Comment by fiona-deriv** [comment]
> Hey @fiona-deriv, map is currently breaking for widths > 1980px. Could you please help to address it even though it's outside the scope?

Hey @sean-binary , investigated this and it's stemming from wrapping the image within **LocalizedLink**, with the current implementation, may take a little longer to refactor, and considering this a bit immediate, can we handle it as an improvement?

**Comment by sean-binary** [comment]
Why aren't we using the google maps iframe for the Paris address since we have that already? @fiona-deriv

**Review by habib-deriv — APPROVED** [review]

**Review by sean-binary — CHANGES_REQUESTED** [review]
Please remove the Paris map now that you're using the Iframe and please use the regular location layout that utilises the Iframe rather than the refactoring new location layout to render the Iframe.

**Review by sean-binary — APPROVED** [review]

**Review by sean-binary — APPROVED** [review]

**Pull request merged**
