### PR TITLE
Aswathy/auto-pull-translation

### PR DESCRIPTION
**Pull request by aswathy-deriv**
Changes:

- Translation for 'stop loss threshold' is not translated in FAQ section of 'How do I control my losses with dbot' on Help center page

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [x] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Comment by DerivFE** [comment]
| Name | Result |
| :--- | :------ |
| **Build status**  | Building 🔨 |
| **Action URL**  | [Visit Action](https://github.com/binary-com/deriv-com/actions/runs/6784225123) |

**Comment by DerivFE** [comment]
| Name | Result |
| :--- | :------ |
| **Build status**  | Building 🔨 |
| **Action URL**  | [Visit Action](https://github.com/binary-com/deriv-com/actions/runs/6784236436) |

**Comment by DerivFE** [comment]
**Preview Link**: https://translation-1627-hel.deriv-com-preview-links.pages.dev
| Name | Result |
| :--- | :------ |
| **Build status**  | Completed ✅ |
| **Preview URL**  | [Visit Preview](https://translation-1627-hel.deriv-com-preview-links.pages.dev) |
| **Action URL**  | [Visit Action](https://github.com/binary-com/deriv-com/actions/runs/6784236436) |

**Comment by DerivFE** [comment]
| Name | Result |
| :--- | :------ |
| **Build status**  | Building 🔨 |
| **Action URL**  | [Visit Action](https://github.com/binary-com/deriv-com/actions/runs/6784777023) |

**Review by meenakshi-deriv — APPROVED** [review]

**Review by prince-deriv — APPROVED** [review]

**Review by mohsen-deriv — APPROVED** [review]

**Pull request merged**
