### PR TITLE
Meenu/fix: added telegram faq

### PR DESCRIPTION
**Pull request by meenakshi-deriv**
Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Review by michio-rework — APPROVED** [review]
can you please coordinate this with @niloo-fs ? 
notify her of these changes please :pray:

**Comment by niloo-fs** [comment]
> can you please coordinate this with @niloo-fs ? notify her of these changes please pray

Thank u for notify me for this

**Review by habib-deriv — DISMISSED** [review]
LGTM

**Review by habib-deriv — CHANGES_REQUESTED** [review]
LGTM

**Pull request merged**
