### PR TITLE
Meenu/Stp 74243 translation for partner page

### PR DESCRIPTION
**Pull request by meenakshi-deriv**
Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Review by NikitK-deriv — DISMISSED** [review]
Good job 👍 
Please resolve branch conflicts 🙏

**Review by michio-rework — DISMISSED** [review]

**Review by prince-deriv — DISMISSED** [review]

**Comment by prince-deriv** [comment]
Can you resolve the conflicts and fix the code smells?

**Review by habib-deriv — APPROVED** [review]
LGTM

**Review by yashim-deriv — DISMISSED** [review]

**Review by habib-deriv — APPROVED** [review]
LGTM

**Pull request merged**
