### PR TITLE
Sean/fix: hero overlapping header for some languages

### PR DESCRIPTION
**Pull request by sean-binary**
Changes:

-   Fix: hero overlapping header for some languages

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Comment by ShuvoHabib** [comment]
Somehow this 'crowdin' language is available here !

Screenshot-20210408123524

**Comment by yashim-deriv** [comment]
@ShuvoHabib  The `crowdin` option in the language selector will only appear in test links~ don't worry 😄 it's for debugging purposes to see which strings are not yet/already translated

**Comment by ShuvoHabib** [comment]
> @ShuvoHabib The `crowdin` option in the language selector will only appear in test links~ don't worry 😄 it's for debugging purposes to see which strings are not yet/already translated

Oh, I see :D ,

**Comment by ShuvoHabib** [comment]
Hi @sean-binary 
For Media Screen 1091, the Hero image gets hidden
Screenshot 2021-04-08 at 12 43 26 PM

**Comment by sean-binary** [comment]
> Hi @sean-binary
> For Media Screen 1091, the Hero image gets hidden
> Screenshot 2021-04-08 at 12 43 26 PM

This seems to work fine for me though.

**Review by kevinw-binary — APPROVED** [review]

**Review by yashim-deriv — APPROVED** [review]

**Pull request merged**
