### PR TITLE
Vijayasree/ Refactor common folder to ts

### PR DESCRIPTION
**Pull request by vijayasree-deriv**
Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [x] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Review by alamin-deriv — APPROVED** [review]

**Review by aswathy-deriv — DISMISSED** [review]
LGTM

**Comment by yashim-deriv** [comment]
Please resolve conflicts @vijayasree-deriv  🙏🏼

**Comment by vijayasree-deriv** [comment]
> Please resolve conflicts @vijayasree-deriv 🙏🏼

done.

**Comment by aswathy-deriv** [comment]
@vijayasree-deriv still there is 2 code smells..can you please check that too

**Comment by vijayasree-deriv** [comment]
> @vijayasree-deriv still there is 2 code smells..can you please check that too

@prince-deriv said to leave the other 2 code smells

**Review by prince-deriv — APPROVED** [review]

**Review by mohammad-rework — APPROVED** [review]

**Pull request closed without merging**
